### ISSUE TITLE
cfg/agent.json  missing

### ISSUE THREAD

**Issue by sreedm** [johnblackford/agent#1]
Hi,

I have pulled the agent code and I see that the directory "agent/cfg"  is missing.
while running agent, in main(), cfg/agent.json file is not available.
can you please add the missing directory.

Thanks,
Sreedevi

**Comment by johnblackford** [comment]
Sreedevi,

Thanks for raising this issue.  The config file is only used when the "product class" is either "RPi_Motion" or "RPi_Camera", which are special installations on a couple of my raspberry pi devices.  I'll add the file later tonight when I get back home.

**Comment by sreedm** [comment]
Thanks John.

John, I see in DB files the below values for controller
Device.LocalAgent.Controller.1.EndpointID": "controller-stomp-johnb"
Device.LocalAgent.Controller.1.MTP.1.STOMP.Destination": "/queue/controller-stomp-johnb"
Device.STOMP.Connection.1.Host": "stomp.johnblackford.org"
so, your controller is running on different machine? and  in the path specified above?

-Sreedevi

**Comment by johnblackford** [comment]
I've added an example config file.

**Comment by johnblackford** [comment]
Regarding the controller, I have an example controller that I was using for testing but it is no longer being maintained and the stomp.johnblackford.org server is also not being maintained.

**Comment by sreedm** [comment]
Thank you.

**Comment by sreedm** [comment]
Hi John,

This  "/queue/controller-stomp-johnb" is just a flat file or process running for controller?
w.r.t the binding between USP and STOMP, i was thinking to actually use the message queues or can be done in any other way.
Any insight on this is really helpful to me.

Thanks,
Sreedevi

**Comment by johnblackford** [comment]
I was using a RabbitMQ server as a STOMP server when I was testing.  The "/queue/controller-stomp-johnb" was a queue on the RabbitMQ server that the test USP Controller was listening to.

**Comment by sreedm** [comment]
Git it. Thanks

**Comment by sreedm** [comment]
Sorry. Got it.

**Comment by sreedm** [comment]
Hi John,

what is purpose that USP Agent sending Periodic Notif messages??
Is this to keep the connection alive between agent and controller?

If so, can the subscription for PeriodicStompNotif can be disabled and can
i enable heartbeats instead?

Thanks,
Sreedevi

**Comment by johnblackford** [comment]
Sreedevi,

Periodic Notification messages are not the same as the connection keep alive.  The connection keep alive is handled at the Message Transfer Protocol (MTP) layer: CoAP, WebSockets, or STOMP.  Actually, CoAP doesn't have persistent connections as it is UDP-based, but STOMP does and has its own keep-alive mechanism (see https://usp.technology/specification/mtp/stomp/#handling_the_stomp_heart_beat_mechanisms ).

The purpose of the Periodic Notification is more to see if there is anything the USP Controller might want to do on a periodic basis (retrieve data, perform diagnostics, etc.).

**Comment by sreedm** [comment]
Hi John,

I don't see the implementation for ADD and DELETE in agent code
(request_handler.py). Do you have the plan to add them into the agent code?
Is there any reason for not being added those functionalities in the code?
if i have to test the ADD/DELETE functionality from my controller , how do
i proceed?

Thanks,
Sreedevi
